// Generated by CoffeeScript 1.6.2
(function() {
  var EventEmitter, Thermometer, argv, config, controlChannels, emitSampleSignal, emitter, gpio, ioCallback, ioChange, sample, sensor, sensors, setupIO, shutdown, statsd, statsdClient, thermo, _i, _len;

  EventEmitter = require('events').EventEmitter;

  statsd = require('node-statsd').StatsD;

  argv = require('optimist').argv;

  gpio = require('rpi-gpio');

  config = require('./lib/config.js');

  Thermometer = require('./lib/thermometer.js');

  thermo = new Thermometer();

  thermo.unit(config.sensorUnit);

  if (argv.sensors) {
    console.log('Querying sensor ids...');
    sensors = thermo.sensors();
    for (_i = 0, _len = sensors.length; _i < _len; _i++) {
      sensor = sensors[_i];
      console.log(sensor);
    }
    return;
  }

  controlChannels = [];

  ioChange = function(channel, value) {
    console.log('Channel ' + channel + ' value is now ' + value);
    controlChannels[channel].locked = false;
    return controlChannels[channel].enabled = value;
  };

  setupIO = function() {
    var _j, _len1, _ref;

    _ref = config.sensors;
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      sensor = _ref[_j];
      if (sensor.control !== "none") {
        gpio.setup(sensor.gpio, gpio.DIR_OUT);
        controlChannels[sensor.gpio] = {
          enabled: false,
          locked: false
        };
      }
    }
    return gpio.on('change', ioChange);
  };

  emitter = new EventEmitter();

  shutdown = false;

  statsdClient = new statsd();

  setupIO();

  ioCallback = function(err) {
    if (err) {
      throw err;
    }
  };

  emitSampleSignal = function() {
    emitter.emit('sample');
  };

  sample = function() {
    var controlName, sensorReading, _j, _len1, _ref;

    _ref = config.sensors;
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      sensor = _ref[_j];
      sensorReading = thermo.temperature(sensor.id);
      if (argv.debug) {
        console.log(sensor.name + '[' + sensor.id + '] : ' + sensorReading);
      }
      if (!argv.nolog) {
        statsdClient.gauge(sensor.name, sensorReading);
      }
      if (sensor.control === "none") {
        continue;
      }
      if (controlChannels[sensor.gpio].locked === true) {
        continue;
      }
      controlName = sensor.name + '_gpio_' + sensor.gpio;
      if (sensor.control === "manual") {
        if (sensorReading > sensor.sv && controlChannels[sensor.gpio].enabled === true) {
          gpio.write(sensor.gpio, false, ioCallback);
          controlChannels[sensor.gpio].locked = true;
          statsdClient.decrement(controlName);
        } else if (sensorReading < sensor.sv && controlChannels[sensor.gpio].enabled === !true) {
          gpio.write(sensor.gpio, true, ioCallback);
          controlChannels[sensor.gpio].locked = true;
          statsdClient.increment(controlName);
        }
      }
    }
    if (!shutdown) {
      setTimeout(emitSampleSignal, config.pollFrequency);
    }
  };

  emitter.on('sample', sample);

  setTimeout(emitSampleSignal, config.pollFrequency);

}).call(this);
