// Generated by CoffeeScript 1.6.2
(function() {
  var Cli, Controller, argv, cli, config, controller;

  argv = require('optimist').argv;

  Cli = require('./lib/cli.js');

  Controller = require('./lib/controller.js');

  config = require('./lib/config.js');

  cli = new Cli();

  if (cli.run(argv)) {
    return;
  }

  controller = new Controller(config, argv.debug, argv.nolog);

  controller.run();

}).call(this);
