// Generated by CoffeeScript 1.6.2
(function() {
  var Buffer, db, mongoose;

  Buffer = require('buffer').Buffer;

  mongoose = require('mongoose');

  db = require('./db.js');

  require('../lib/orm/user.js');

  exports.getAuthToken = function(req) {
    var auth, header, method, parts, token;

    header = req.headers['authorization'] || '';
    parts = header.split(/\s+/);
    token = parts.pop() || '';
    method = parts.shift() || '';
    if (method !== 'Bearer') {
      return null;
    }
    auth = new Buffer(token, 'base64').toString();
    return auth;
  };

  exports.checkAuthToken = function(token, callback) {
    var authCallback, model;

    model = mongoose.model('User');
    authCallback = function(err, model) {
      if (model !== void 0) {
        return callback(true);
      } else {
        return callback(false);
      }
    };
    return model.findOne({
      access_token: token
    }, authCallback);
  };

}).call(this);
