// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    pollFrequency: 100,
    sensors: [
      {
        ambient: {
          id: '000004bcb49a',
          gpio: 4
        },
        fermenter_1: {
          id: '000004bd452f',
          gpio: 4
        },
        fermenter_2: {
          id: '000004bd9529',
          gpio: 4
        }
      }
    ]
  };

}).call(this);
