// Generated by CoffeeScript 1.6.2
(function() {
  var db, express, logger, mongoose, profileRouter;

  express = require('express');

  mongoose = require('mongoose');

  logger = require('./services/logger.js').logger;

  profileRouter = require('./routes/profile.js');

  db = require('./services/db.js');

  exports.configure = function(Express, app) {
    var NotFound;

    app.configure(function() {
      logger.info('Configuring application...');
      app.use(Express.logger({
        buffer: true
      }));
      app.use(Express.methodOverride());
      app.use(Express.bodyParser());
      app.use(Express.cookieParser());
      app.use(Express.responseTime());
      profileRouter.routes(app);
      app.set('log', 'logs/rpi-ferment.log');
      db.establishConnection();
    });
    app.configure('development', function() {
      logger.info('Configuring development mode...');
      app.use(Express.errorHandler({
        dumpExceptions: true,
        showStack: true
      }));
    });
    app.configure('production', function() {
      logger.info('Configuring production mode...');
      app.use(Express.errorHandler);
    });
    NotFound = function(msg) {
      this.name = 'NotFound';
      logger.info('Not Found - ' + msg);
      Error.call(this, msg);
      Error.captureStackTrace(this, arguments.callee);
    };
    NotFound.prototype.__proto__ = Error.prototype;
    app.get('/404', function(req, res) {
      throw new NotFound('page not found');
    });
    app.get('/500', function(req, res) {
      throw new Error('keyboard cat!');
    });
    return app.use(function(err, req, res, next) {
      logger.error(err);
      if (err instanceof NotFound) {
        res.send({
          status: 404,
          error: err
        });
      } else {
        res.send({
          status: 500,
          error: err
        });
      }
    });
  };

}).call(this);
