// Generated by CoffeeScript 1.6.2
(function() {
  var Sockets, auth, db, http, socketio,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  http = require('http');

  socketio = require('socket.io');

  auth = require('./services/auth.js');

  db = require('./services/db.js');

  Sockets = (function() {
    Sockets.prototype.controller_ = null;

    Sockets.prototype.io_ = null;

    function Sockets(controller) {
      this.connectionHandler = __bind(this.connectionHandler, this);
      this.run = __bind(this.run, this);      this.controller_ = controller;
    }

    Sockets.prototype.httpHandler = function(req, res) {
      res.writeHead(200);
      res.end('');
    };

    Sockets.prototype.checkPermission = function(access_token, callback) {
      var authCallback;

      authCallback = function(authed) {
        if (authed === true) {
          return callback();
        }
      };
      auth.checkAuthToken(access_token, callback);
    };

    Sockets.prototype.run = function() {
      var app, config;

      config = this.controller_.config();
      if (this.controller_.debug()) {
        console.log('Listening for socket connections on port [' + config.ioPort + '] ...');
      }
      app = http.createServer(this.httpHandler);
      this.io_ = socketio.listen(app);
      app.listen(config.ioPort);
      this.io_.sockets.on('connection', this.connectionHandler);
    };

    Sockets.prototype.connectionHandler = function(socket) {
      var _this = this;

      socket.on('config', function() {
        if (_this.controller_.debug()) {
          console.log('Socket requested config');
        }
        socket.emit('config', _this.controller_.config());
      });
      socket.on('getgpio', function(channel) {
        var data, state;

        state = _this.controller_.getGpio(channel);
        data = {
          channel: channel,
          state: state
        };
        socket.emit('gpio', data);
      });
      socket.on('setgpio', function(channel, state, access_token) {
        var setGpioCallback;

        setGpioCallback = function() {
          if (this.controller_.debug()) {
            console.log('Socket requested GPIO channel [' + channel + '] set to state [' + state + ']');
          }
          return this.controller_.setGpio(channel, state);
        };
        _this.checkPermission(access_token, setGpioCallback);
      });
      socket.on('setsv', function(sensor, sv, access_token) {
        var setSvCallback;

        setSvCallback = function() {
          if (this.controller_.debug()) {
            console.log('Socket requested sensor [' + sensor + '] SV set to [' + sv + ']');
          }
          return this.controller_.setSv(sensor, sv);
        };
        _this.checkPermission(access_token, setSvCallback);
      });
      socket.on('getsv', function(sensor) {
        var data, sv;

        sv = _this.controller_.getSv(sensor);
        data = {
          sensor: sensor,
          sv: sv
        };
        socket.emit('sv', data);
      });
      socket.on('getpv', function(sensor) {
        var data, pv;

        pv = _this.controller_.getPv(sensor);
        data = {
          sensor: sensor,
          pv: pv
        };
        socket.emit('pv', data);
      });
      socket.on('getmode', function(sensor) {
        var data, mode;

        mode = _this.controller_.getMode(sensor);
        data = {
          sensor: sensor,
          mode: mode
        };
        socket.emit('mode', data);
      });
      socket.on('setmode', function(sensor, mode, access_token) {
        var setModeCallback;

        setModeCallback = function() {
          if (this.controller_.debug()) {
            console.log('Socket requested sensor [' + sensor('] set to mode [' + mode + ']'));
          }
          return this.controller_.setMode(sensor, mode);
        };
        return _this.checkPermission(access_token, setModeCallback);
      });
    };

    return Sockets;

  })();

  module.exports = Sockets;

}).call(this);
