// Generated by CoffeeScript 1.6.2
(function() {
  var bcrypt, mongoose;

  mongoose = require('mongoose');

  bcrypt = require('bcrypt');

  require('../orm/user.js');

  module.exports.routes = function(app) {
    return app.post('/session', function(req, res) {
      var findCallback, model;

      model = mongoose.model('User');
      findCallback = function(error, result) {
        if (error) {
          return;
        }
        if (result) {
          if (bcrypt.compareSync(req.body.password, result.password)) {
            return res.send({
              id: result._id
            });
          } else {
            return res.send({});
          }
        }
      };
      model.findOne({
        email: req.body.email
      }, findCallback);
    });
  };

}).call(this);
