// Generated by CoffeeScript 1.6.2
(function() {
  var Profile, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  Profile = new Schema;

  Profile.add({
    name: {
      type: String,
      required: true
    },
    control_mode: String,
    sensor: String,
    start_time: Date,
    steps: [
      {
        name: String,
        duration: Number,
        unit: String,
        start_temperature: Number,
        end_temperature: Number,
        order: Number,
        completed: Boolean,
        start_time: Date,
        end_time: Date,
        active: Boolean
      }
    ],
    overrides: [
      {
        action: String,
        time: Date
      }
    ],
    history: [
      {
        action: String,
        state: String,
        time: Date
      }
    ],
    updated_at: Boolean,
    active: Boolean,
    created_at: {
      type: Date,
      "default": Date.now
    }
  });

  mongoose.model('Profile', Profile);

}).call(this);
